---
title: "0_fieldwork_stats.Rmd"
author: "Andrea Estandia"
date: "13/02/2024"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup}
# Knitr settings: 
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
options(scipen = 999)
```

```{r}
source("./src/0.0_winter-moth_source.R")
```

Read data with adult moths
```{r}
tree <-
  read_csv(file.path(data_path,
                     "dfs",
                     "tree_coordinates.csv")) %>% 
  #remove spaces and upper cases in column names
  janitor::clean_names() %>% 
  select(-area, -plot) %>% 
  rename(tree_species=species)

df <-
  read_csv(file.path(data_path,
                     "dfs",
                     "WM_samples_2023.csv")) %>% 
  #remove spaces and upper cases in column names
  janitor::clean_names() %>% 
  mutate(tree_id=as.character(tree_id)) %>% 
  left_join(tree, by="tree_id") 
```

Summary statistics by species, sex, eggs
```{r}
summary_df <-df %>% 
  group_by(species, sex, treatment) %>% 
  summarise(n=n())

write.csv(summary_df,
          file.path(reports_path,
                    "summary_fieldwork-WM_2023.csv"),
          row.names = F)
```

Read data with water traps
```{r}
wm_caterpillars <-
  read_csv(file.path(data_path,
                     "dfs",
                     "caterpillars_2023.csv")) %>% 
  filter(totalwm>0) %>% 
  left_join(tree, by="tree_id") 
```


Map representing where the samples are
```{r}
shape <- 
  read_sf(dsn = file.path(data_path,
                                 "wytham_map",
                                 "perimeter.shp"))

df_sf <- st_as_sf(drop_na(df, x), 
                  coords = c("x", 
                             "y"), 
                  crs = st_crs(4326))

df_sf$geometry <- 
  st_transform(df_sf$geometry, 
               crs=st_crs(shape))

wm_caterpillars_sf <-
  st_as_sf(drop_na(wm_caterpillars, x, y), 
                  coords = c("x", 
                             "y"), 
                  crs = st_crs(4326))

wm_caterpillars_sf$geometry <- 
  st_transform(wm_caterpillars_sf$geometry, 
               crs=st_crs(shape))
```

```{r}
pal <- wesanderson::wes_palette("Zissou1", n=50,type="continuous")
```

```{r}
ggplot() +
  geom_sf(data = shape, fill = "lightgrey", color = "lightgrey", size = 0) +
  geom_sf(data = wm_caterpillars_sf, aes(color = tree_species), size = 2) +
  theme_minimal() +
  #scale_color_gradientn(colours=pal) +
    labs(title = NULL, subtitle = NULL, x = "\nEasting\n", y = "\nNorthing\n") +
    theme_minimal() +
    theme(
      plot.background = element_rect(fill = "transparent", color = NA),
      panel.grid = element_blank(),
      panel.background = element_blank(),
      axis.line = element_line(colour = "black"),
      text = element_text(family = "Calibri"),
      axis.title = element_text(family = "Calibri"),
      legend.position = "bottom"
    )+
  labs(title="Winter moths")#+gghighlight(tree_species=="beech")

zoom_coords <- c(xmin = 445919.4, 
                 xmax = 208499.9, 
                 ymin = 445919.4, 
                 ymax = 208499.9)

ggplot() +
  geom_sf(data = shape, fill = "lightgrey", color = "lightgrey", size = 0) +
  geom_sf(data = df_sf, aes(color = wm_species), size = 2) +
  theme_minimal() +
  scale_color_discrete() +
    labs(title = NULL, subtitle = NULL, x = "\nEasting\n", y = "\nNorthing\n") +
    theme_minimal() +
    theme(
      plot.background = element_rect(fill = "transparent", color = NA),
      panel.grid = element_blank(),
      panel.background = element_blank(),
      axis.line = element_line(colour = "black"),
      text = element_text(family = "Calibri"),
      axis.title = element_text(family = "Calibri"),
      legend.position = "bottom"
    ) +
  coord_sf(xlim = c(zoom_coords[1], zoom_coords[2]),
           ylim = c(zoom_coords[3], zoom_coords[4]))
```

